### PR TITLE
Import react-contextmenu

### PR DESCRIPTION
**Pull request by pvh**
I know it says "vendor", but I suspect we'll continue to rewrite this component over time. At this point I've: stripped it down to just a biggish component, prettier'ed it, fixed all the eslint errors, and moved the type into the `types` directory.

### CODE REVIEW

**Comment by mjtognetti** [comment]
Would be nice to move this `src/node_modules`, then we can import simpler as `import Blah from "react-contextmenu"`

**Comment by mjtognetti** [comment]
Creates a nice division between code/components we've written ourselves and vendored deps.

**Comment by pvh** [comment]
Well, what I said to Jeff is what I'll say here: this isn't a vendored dep. It's been reformatted and modified to fit our coding conventions and all the module infrastructure has been stripped out. Still, if you want to move it, that's fine with me, it just seems slightly confusing to someone stumbling across it. If you do this, also move react-colorpicker (and we should probably move the other bits in and remove the upstream dependency.)

**Comment by jeffpeterson** [comment]
> It's been reformatted and modified to fit our coding conventions and all the module infrastructure has been stripped out.
I guess I assume that, given that it isn't just installed as an npm package.

> also move react-colorpicker
For sure! And `react-simple-dropdown` and probably `line-awesome`

> it just seems slightly confusing to someone stumbling across it.
Yeah, we can add a `src/node_modules/readme.md` to briefly explain what's in there and why.

I think we can merge this and then move all of them.

**Pull request merged**
